name: Selenium tests

on: push

jobs:
  running_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Save allure-results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate_and_publish_report:
    runs-on: ubuntu-latest
    needs: running_tests
    name: Generate reports

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      # Allure installation
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz && sudo tar -zxsf allure-2.34.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.34.1/bin/allure /usr/bin/allure

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - run: allure generate -c allure-results -o _site

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4